<?php
session_start();
define('incl_path','../../global/libs/');
define('libs_path','../../libs/');
require_once(incl_path.'gfconfig.php');
require_once(incl_path.'gfinit.php');
require_once(incl_path.'gffunc.php');
require_once(incl_path.'gffunc_member.php');
require_once(libs_path.'cls.mysql.php');
$json 	= json_decode(file_get_contents('php://input'),true);
$data	= json_decode(decrypt($json['data'],PIT_API_KEY),true);
$user=$data['username'];
$arr=array();
$arr['fullname']=antiData($data['fullname']);
$arr['phone']=antiData($data['phone']);
$arr['cmt']=antiData($data['cmt']);
$arr['cmt_date']=antiData($data['cmt_date']);
$arr['cmt_place']=antiData($data['cmt_place']);
SysEdit('tbl_member',$arr," username='$user'");
echo json_encode(array('status'=>'yes','mess'=>'success!'));
die();
